CREATE TABLE IF NOT EXISTS TIMETRACK_BREAK (
	TTB_ref			INTEGER PRIMARY KEY,
	TT_ref			INTEGER		,
	TTB_startTime	DATE		NOT NULL,
	TTB_endTime		DATE		NOT NULL,
	FOREIGN KEY (TT_ref) references TIMETRACK (TT_ref)
);
